INSERT INTO "public"."currency" ("id", "name", "iso", "symbol") VALUES
        (1, 'US Dollar', 'USD', '$'),
        (2, 'Swiss franc', 'CHF', 'NULL'),
        (3, 'Euro', 'EUR', '€'),
        (4, 'Renminbi', 'CNY', '¥'),
        (5, 'Leke', 'ALL', 'Lek'),
        (6, 'Dollars', 'USD', '$'),
        (7, 'Afghanis', 'AFN', '؋'),
        (8, 'Pesos', 'ARS', '$'),
        (9, 'Guilders', 'AWG', 'ƒ'),
        (10, 'Dollars', 'AUD', '$'),
        (11, 'New Manats', 'AZN', 'ман'),
        (12, 'Dollars', 'BSD', '$'),
        (13, 'Dollars', 'BBD', '$'),
        (14, 'Rubles', 'BYR', 'p.'),
        (15, 'Euro', 'EUR', '€'),
        (16, 'Dollars', 'BZD', 'BZ$'),
        (17, 'Dollars', 'BMD', '$'),
        (18, 'Bolivianos', 'BOB', '$b'),
        (19, 'Convertible Marka', 'BAM', 'KM'),
        (20, 'Pula', 'BWP', 'P'),
        (21, 'Leva', 'BGN', 'лв'),
        (22, 'Reais', 'BRL', 'R$'),
        (23, 'Pounds', 'GBP', '£'),
        (24, 'Dollars', 'BND', '$'),
        (25, 'Riels', 'KHR', '៛'),
        (26, 'Dollars', 'CAD', '$'),
        (27, 'Dollars', 'KYD', '$'),
        (28, 'Pesos', 'CLP', '$'),
        (29, 'Yuan Renminbi', 'CNY', '¥'),
        (30, 'Pesos', 'COP', '$'),
        (31, 'Colón', 'CRC', '₡'),
        (32, 'Kuna', 'HRK', 'kn'),
        (33, 'Pesos', 'CUP', '₱'),
        (34, 'Koruny', 'CZK', 'Kč'),
        (35, 'Kroner', 'DKK', 'kr'),
        (36, 'Pesos', 'DOP ', 'RD$'),
        (37, 'Dollars', 'XCD', '$'),
        (38, 'Pounds', 'EGP', '£'),
        (39, 'Colones', 'SVC', '$'),
        (40, 'Pounds', 'FKP', '£'),
        (41, 'Dollars', 'FJD', '$'),
        (42, 'Cedis', 'GHC', '¢'),
        (43, 'Pounds', 'GIP', '£'),
        (44, 'Quetzales', 'GTQ', 'Q'),
        (45, 'Pounds', 'GGP', '£'),
        (46, 'Dollars', 'GYD', '$'),
        (47, 'Lempiras', 'HNL', 'L'),
        (48, 'Dollars', 'HKD', '$'),
        (49, 'Forint', 'HUF', 'Ft'),
        (50, 'Kronur', 'ISK', 'kr'),
        (51, 'Rupees', 'INR', 'Rp'),
        (52, 'Rupiahs', 'IDR', 'Rp'),
        (53, 'Rials', 'IRR', '﷼'),
        (54, 'Pounds', 'IMP', '£'),
        (55, 'New Shekels', 'ILS', '₪'),
        (56, 'Dollars', 'JMD', 'J$'),
        (57, 'Yen', 'JPY', '¥'),
        (58, 'Pounds', 'JEP', '£'),
        (59, 'Tenge', 'KZT', 'лв'),
        (60, 'Won', 'KPW', '₩'),
        (61, 'Won', 'KRW', '₩'),
        (62, 'Soms', 'KGS', 'лв'),
        (63, 'Kips', 'LAK', '₭'),
        (64, 'Lati', 'LVL', 'Ls'),
        (65, 'Pounds', 'LBP', '£'),
        (66, 'Dollars', 'LRD', '$'),
        (67, 'Switzerland Francs', 'CHF', 'CHF'),
        (68, 'Litai', 'LTL', 'Lt'),
        (69, 'Denars', 'MKD', 'ден'),
        (70, 'Ringgits', 'MYR', 'RM'),
        (71, 'Rupees', 'MUR', '₨'),
        (72, 'Pesos', 'MXN', '$'),
        (73, 'Tugriks', 'MNT', '₮'),
        (74, 'Meticais', 'MZN', 'MT'),
        (75, 'Dollars', 'NAD', '$'),
        (76, 'Rupees', 'NPR', '₨'),
        (77, 'Guilders', 'ANG', 'ƒ'),
        (78, 'Dollars', 'NZD', '$'),
        (79, 'Cordobas', 'NIO', 'C$'),
        (80, 'Nairas', 'NGN', '₦'),
        (81, 'Krone', 'NOK', 'kr'),
        (82, 'Rials', 'OMR', '﷼'),
        (83, 'Rupees', 'PKR', '₨'),
        (84, 'Balboa', 'PAB', 'B/.'),
        (85, 'Guarani', 'PYG', 'Gs'),
        (86, 'Nuevos Soles', 'PEN', 'S/.'),
        (87, 'Pesos', 'PHP', 'Php'),
        (88, 'Zlotych', 'PLN', 'zł'),
        (89, 'Rials', 'QAR', '﷼'),
        (90, 'New Lei', 'RON', 'lei'),
        (91, 'Rubles', 'RUB', 'руб'),
        (92, 'Pounds', 'SHP', '£'),
        (93, 'Riyals', 'SAR', '﷼'),
        (94, 'Dinars', 'RSD', 'Дин.'),
        (95, 'Rupees', 'SCR', '₨'),
        (96, 'Dollars', 'SGD', '$'),
        (97, 'Dollars', 'SBD', '$'),
        (98, 'Shillings', 'SOS', 'S'),
        (99, 'Rand', 'ZAR', 'R'),
        (100, 'Rupees', 'LKR', '₨'),
        (101, 'Kronor', 'SEK', 'kr'),
        (102, 'Dollars', 'SRD', '$'),
        (103, 'Pounds', 'SYP', '£'),
        (104, 'New Dollars', 'TWD', 'NT$'),
        (105, 'Baht', 'THB', '฿'),
        (106, 'Dollars', 'TTD', 'TT$'),
        (107, 'Lira', 'TRY', '₺'),
        (108, 'Liras', 'TRL', '£'),
        (109, 'Dollars', 'TVD', '$'),
        (110, 'Hryvnia', 'UAH', '₴'),
        (111, 'Pesos', 'UYU', '$U'),
        (112, 'Sums', 'UZS', 'лв'),
        (113, 'Bolivares Fuertes', 'VEF', 'Bs'),
        (114, 'Dong', 'VND', '₫'),
        (115, 'Rials', 'YER', '﷼'),
        (116, 'Zimbabwe Dollars', 'ZWD', 'Z$'),
        (117, 'Rupees', 'INR', '₹');
