alter table "public"."Contact" drop constraint "Contact_account_id_fkey";

create table "public"."account_contact" (
    "id" bigint generated by default as identity not null,
    "account_id" integer not null,
    "contact_id" integer not null,
    "relationship" smallint not null,
    "untill" date,
    "since" date not null default now()
);


alter table "public"."account_contact" enable row level security;

create table "public"."relationship" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text not null
);


alter table "public"."relationship" enable row level security;

alter table "public"."Account" alter column "country" set data type text using "country"::text;

alter table "public"."Account" alter column "description" set data type text using "description"::text;

alter table "public"."Account" alter column "email" set not null;

alter table "public"."Account" alter column "email" set data type text using "email"::text;

alter table "public"."Account" alter column "name" set data type text using "name"::text;

alter table "public"."Account" alter column "website" set data type text using "website"::text;

alter table "public"."Contact" drop column "accountId";

alter table "public"."Contact" drop column "account_id";

alter table "public"."Contact" add column "firstName" text;

alter table "public"."Contact" add column "lastname" text not null;

alter table "public"."Contact" add column "personality" text;

CREATE UNIQUE INDEX account_contact_pkey ON public.account_contact USING btree (id);

CREATE UNIQUE INDEX relationship_name_key ON public.relationship USING btree (name);

CREATE UNIQUE INDEX relationship_pkey ON public.relationship USING btree (id);

alter table "public"."account_contact" add constraint "account_contact_pkey" PRIMARY KEY using index "account_contact_pkey";

alter table "public"."relationship" add constraint "relationship_pkey" PRIMARY KEY using index "relationship_pkey";

alter table "public"."account_contact" add constraint "public_account_contact_account_id_fkey" FOREIGN KEY (account_id) REFERENCES "Account"(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."account_contact" validate constraint "public_account_contact_account_id_fkey";

alter table "public"."account_contact" add constraint "public_account_contact_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES "Contact"(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."account_contact" validate constraint "public_account_contact_contact_id_fkey";

alter table "public"."account_contact" add constraint "public_account_contact_relationship_fkey" FOREIGN KEY (relationship) REFERENCES relationship(id) ON UPDATE CASCADE not valid;

alter table "public"."account_contact" validate constraint "public_account_contact_relationship_fkey";

alter table "public"."relationship" add constraint "relationship_name_key" UNIQUE using index "relationship_name_key";

grant delete on table "public"."account_contact" to "anon";

grant insert on table "public"."account_contact" to "anon";

grant references on table "public"."account_contact" to "anon";

grant select on table "public"."account_contact" to "anon";

grant trigger on table "public"."account_contact" to "anon";

grant truncate on table "public"."account_contact" to "anon";

grant update on table "public"."account_contact" to "anon";

grant delete on table "public"."account_contact" to "authenticated";

grant insert on table "public"."account_contact" to "authenticated";

grant references on table "public"."account_contact" to "authenticated";

grant select on table "public"."account_contact" to "authenticated";

grant trigger on table "public"."account_contact" to "authenticated";

grant truncate on table "public"."account_contact" to "authenticated";

grant update on table "public"."account_contact" to "authenticated";

grant delete on table "public"."account_contact" to "service_role";

grant insert on table "public"."account_contact" to "service_role";

grant references on table "public"."account_contact" to "service_role";

grant select on table "public"."account_contact" to "service_role";

grant trigger on table "public"."account_contact" to "service_role";

grant truncate on table "public"."account_contact" to "service_role";

grant update on table "public"."account_contact" to "service_role";

grant delete on table "public"."relationship" to "anon";

grant insert on table "public"."relationship" to "anon";

grant references on table "public"."relationship" to "anon";

grant select on table "public"."relationship" to "anon";

grant trigger on table "public"."relationship" to "anon";

grant truncate on table "public"."relationship" to "anon";

grant update on table "public"."relationship" to "anon";

grant delete on table "public"."relationship" to "authenticated";

grant insert on table "public"."relationship" to "authenticated";

grant references on table "public"."relationship" to "authenticated";

grant select on table "public"."relationship" to "authenticated";

grant trigger on table "public"."relationship" to "authenticated";

grant truncate on table "public"."relationship" to "authenticated";

grant update on table "public"."relationship" to "authenticated";

grant delete on table "public"."relationship" to "service_role";

grant insert on table "public"."relationship" to "service_role";

grant references on table "public"."relationship" to "service_role";

grant select on table "public"."relationship" to "service_role";

grant trigger on table "public"."relationship" to "service_role";

grant truncate on table "public"."relationship" to "service_role";

grant update on table "public"."relationship" to "service_role";


