create table "public"."Product_Category" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "colour_hex" character varying
);


alter table "public"."Product" add column "category" bigint;

CREATE UNIQUE INDEX "Product_Category_name_key" ON public."Product_Category" USING btree (name);

CREATE UNIQUE INDEX "Product_Category_pkey" ON public."Product_Category" USING btree (id);

alter table "public"."Product_Category" add constraint "Product_Category_pkey" PRIMARY KEY using index "Product_Category_pkey";

alter table "public"."Product" add constraint "public_Product_category_fkey" FOREIGN KEY (category) REFERENCES "Product_Category"(id) not valid;

alter table "public"."Product" validate constraint "public_Product_category_fkey";

alter table "public"."Product_Category" add constraint "Product_Category_name_key" UNIQUE using index "Product_Category_name_key";

grant delete on table "public"."Product_Category" to "anon";

grant insert on table "public"."Product_Category" to "anon";

grant references on table "public"."Product_Category" to "anon";

grant select on table "public"."Product_Category" to "anon";

grant trigger on table "public"."Product_Category" to "anon";

grant truncate on table "public"."Product_Category" to "anon";

grant update on table "public"."Product_Category" to "anon";

grant delete on table "public"."Product_Category" to "authenticated";

grant insert on table "public"."Product_Category" to "authenticated";

grant references on table "public"."Product_Category" to "authenticated";

grant select on table "public"."Product_Category" to "authenticated";

grant trigger on table "public"."Product_Category" to "authenticated";

grant truncate on table "public"."Product_Category" to "authenticated";

grant update on table "public"."Product_Category" to "authenticated";

grant delete on table "public"."Product_Category" to "service_role";

grant insert on table "public"."Product_Category" to "service_role";

grant references on table "public"."Product_Category" to "service_role";

grant select on table "public"."Product_Category" to "service_role";

grant trigger on table "public"."Product_Category" to "service_role";

grant truncate on table "public"."Product_Category" to "service_role";

grant update on table "public"."Product_Category" to "service_role";


