create table "public"."lead" (
    "id" bigint generated by default as identity not null,
    "contact" integer not null
);


alter table "public"."lead" enable row level security;

create table "public"."opportunity" (
    "id" bigint generated by default as identity not null,
    "buyer" integer not null,
    "contact" integer not null
);


alter table "public"."opportunity" enable row level security;

create table "public"."product_properties" (
    "id" bigint generated by default as identity not null,
    "productId" integer not null,
    "weight" integer,
    "x" integer,
    "y" integer,
    "z" integer,
    "material" text
);


alter table "public"."product_properties" enable row level security;

alter table "public"."product_component" add column "quantity" smallint not null default '1'::smallint;

alter table "public"."product_image" add column "description" text;

alter table "public"."product_image" add column "title" text;

CREATE UNIQUE INDEX lead_pkey ON public.lead USING btree (id);

CREATE UNIQUE INDEX opportunity_pkey ON public.opportunity USING btree (id);

CREATE UNIQUE INDEX product_properties_pkey ON public.product_properties USING btree (id);

alter table "public"."lead" add constraint "lead_pkey" PRIMARY KEY using index "lead_pkey";

alter table "public"."opportunity" add constraint "opportunity_pkey" PRIMARY KEY using index "opportunity_pkey";

alter table "public"."product_properties" add constraint "product_properties_pkey" PRIMARY KEY using index "product_properties_pkey";

alter table "public"."lead" add constraint "public_lead_contact_fkey" FOREIGN KEY (contact) REFERENCES contact(id) not valid;

alter table "public"."lead" validate constraint "public_lead_contact_fkey";

alter table "public"."opportunity" add constraint "public_opportunity_buyer_fkey" FOREIGN KEY (buyer) REFERENCES account(id) not valid;

alter table "public"."opportunity" validate constraint "public_opportunity_buyer_fkey";

alter table "public"."opportunity" add constraint "public_opportunity_contact_fkey" FOREIGN KEY (contact) REFERENCES contact(id) not valid;

alter table "public"."opportunity" validate constraint "public_opportunity_contact_fkey";

alter table "public"."product_properties" add constraint "public_product_properties_productId_fkey" FOREIGN KEY ("productId") REFERENCES product(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."product_properties" validate constraint "public_product_properties_productId_fkey";

grant delete on table "public"."lead" to "anon";

grant insert on table "public"."lead" to "anon";

grant references on table "public"."lead" to "anon";

grant select on table "public"."lead" to "anon";

grant trigger on table "public"."lead" to "anon";

grant truncate on table "public"."lead" to "anon";

grant update on table "public"."lead" to "anon";

grant delete on table "public"."lead" to "authenticated";

grant insert on table "public"."lead" to "authenticated";

grant references on table "public"."lead" to "authenticated";

grant select on table "public"."lead" to "authenticated";

grant trigger on table "public"."lead" to "authenticated";

grant truncate on table "public"."lead" to "authenticated";

grant update on table "public"."lead" to "authenticated";

grant delete on table "public"."lead" to "service_role";

grant insert on table "public"."lead" to "service_role";

grant references on table "public"."lead" to "service_role";

grant select on table "public"."lead" to "service_role";

grant trigger on table "public"."lead" to "service_role";

grant truncate on table "public"."lead" to "service_role";

grant update on table "public"."lead" to "service_role";

grant delete on table "public"."opportunity" to "anon";

grant insert on table "public"."opportunity" to "anon";

grant references on table "public"."opportunity" to "anon";

grant select on table "public"."opportunity" to "anon";

grant trigger on table "public"."opportunity" to "anon";

grant truncate on table "public"."opportunity" to "anon";

grant update on table "public"."opportunity" to "anon";

grant delete on table "public"."opportunity" to "authenticated";

grant insert on table "public"."opportunity" to "authenticated";

grant references on table "public"."opportunity" to "authenticated";

grant select on table "public"."opportunity" to "authenticated";

grant trigger on table "public"."opportunity" to "authenticated";

grant truncate on table "public"."opportunity" to "authenticated";

grant update on table "public"."opportunity" to "authenticated";

grant delete on table "public"."opportunity" to "service_role";

grant insert on table "public"."opportunity" to "service_role";

grant references on table "public"."opportunity" to "service_role";

grant select on table "public"."opportunity" to "service_role";

grant trigger on table "public"."opportunity" to "service_role";

grant truncate on table "public"."opportunity" to "service_role";

grant update on table "public"."opportunity" to "service_role";

grant delete on table "public"."product_properties" to "anon";

grant insert on table "public"."product_properties" to "anon";

grant references on table "public"."product_properties" to "anon";

grant select on table "public"."product_properties" to "anon";

grant trigger on table "public"."product_properties" to "anon";

grant truncate on table "public"."product_properties" to "anon";

grant update on table "public"."product_properties" to "anon";

grant delete on table "public"."product_properties" to "authenticated";

grant insert on table "public"."product_properties" to "authenticated";

grant references on table "public"."product_properties" to "authenticated";

grant select on table "public"."product_properties" to "authenticated";

grant trigger on table "public"."product_properties" to "authenticated";

grant truncate on table "public"."product_properties" to "authenticated";

grant update on table "public"."product_properties" to "authenticated";

grant delete on table "public"."product_properties" to "service_role";

grant insert on table "public"."product_properties" to "service_role";

grant references on table "public"."product_properties" to "service_role";

grant select on table "public"."product_properties" to "service_role";

grant trigger on table "public"."product_properties" to "service_role";

grant truncate on table "public"."product_properties" to "service_role";

grant update on table "public"."product_properties" to "service_role";


