

create table "public"."country" (
    "id" smallint generated by default as identity not null,
    "iso" text not null,
    "iso3" text,
    "name" text not null,
    "nicename" text not null,
    "numcode" smallint,
    "phonecode" smallint
);


alter table "public"."country" enable row level security;

create table "public"."currency" (
    "id" smallint generated by default as identity not null,
    "name" text not null default 'US Dollar'::text,
    "iso" text not null default 'USD'::text,
    "symbol" text not null default 'NULL'::text
);


alter table "public"."currency" enable row level security;

create table "public"."price" (
    "id" bigint generated by default as identity not null,
    "price" real not null,
    "currency" "Currency" not null default 'USD'::"Currency"
);


alter table "public"."price" enable row level security;

create table "public"."product_image" (
    "id" bigint generated by default as identity not null,
    "productId" integer not null,
    "coverImage" boolean not null default false,
    "filePath" text not null
);


alter table "public"."product_image" enable row level security;

alter table "public"."Account" alter column "country" set default '25'::smallint;

alter table "public"."Account" alter column "country" set data type smallint using "country"::smallint;

alter table "public"."Contact" enable row level security;

alter table "public"."Post" enable row level security;

alter table "public"."Product_Category" enable row level security;

CREATE UNIQUE INDEX country_pkey ON public.country USING btree (id);

CREATE UNIQUE INDEX currency_pkey ON public.currency USING btree (id);

CREATE UNIQUE INDEX price_pkey ON public.price USING btree (id);

CREATE UNIQUE INDEX product_image_pkey ON public.product_image USING btree (id);

alter table "public"."country" add constraint "country_pkey" PRIMARY KEY using index "country_pkey";

alter table "public"."currency" add constraint "currency_pkey" PRIMARY KEY using index "currency_pkey";

alter table "public"."price" add constraint "price_pkey" PRIMARY KEY using index "price_pkey";

alter table "public"."product_image" add constraint "product_image_pkey" PRIMARY KEY using index "product_image_pkey";

alter table "public"."Account" add constraint "public_Account_country_fkey" FOREIGN KEY (country) REFERENCES country(id) ON UPDATE CASCADE not valid;

alter table "public"."Account" validate constraint "public_Account_country_fkey";

alter table "public"."product_image" add constraint "public_product_image_productId_fkey" FOREIGN KEY ("productId") REFERENCES "product"(id) ON DELETE CASCADE not valid;

alter table "public"."product_image" validate constraint "public_product_image_productId_fkey";

grant delete on table "public"."country" to "anon";

grant insert on table "public"."country" to "anon";

grant references on table "public"."country" to "anon";

grant select on table "public"."country" to "anon";

grant trigger on table "public"."country" to "anon";

grant truncate on table "public"."country" to "anon";

grant update on table "public"."country" to "anon";

grant delete on table "public"."country" to "authenticated";

grant insert on table "public"."country" to "authenticated";

grant references on table "public"."country" to "authenticated";

grant select on table "public"."country" to "authenticated";

grant trigger on table "public"."country" to "authenticated";

grant truncate on table "public"."country" to "authenticated";

grant update on table "public"."country" to "authenticated";

grant delete on table "public"."country" to "service_role";

grant insert on table "public"."country" to "service_role";

grant references on table "public"."country" to "service_role";

grant select on table "public"."country" to "service_role";

grant trigger on table "public"."country" to "service_role";

grant truncate on table "public"."country" to "service_role";

grant update on table "public"."country" to "service_role";

grant delete on table "public"."currency" to "anon";

grant insert on table "public"."currency" to "anon";

grant references on table "public"."currency" to "anon";

grant select on table "public"."currency" to "anon";

grant trigger on table "public"."currency" to "anon";

grant truncate on table "public"."currency" to "anon";

grant update on table "public"."currency" to "anon";

grant delete on table "public"."currency" to "authenticated";

grant insert on table "public"."currency" to "authenticated";

grant references on table "public"."currency" to "authenticated";

grant select on table "public"."currency" to "authenticated";

grant trigger on table "public"."currency" to "authenticated";

grant truncate on table "public"."currency" to "authenticated";

grant update on table "public"."currency" to "authenticated";

grant delete on table "public"."currency" to "service_role";

grant insert on table "public"."currency" to "service_role";

grant references on table "public"."currency" to "service_role";

grant select on table "public"."currency" to "service_role";

grant trigger on table "public"."currency" to "service_role";

grant truncate on table "public"."currency" to "service_role";

grant update on table "public"."currency" to "service_role";

grant delete on table "public"."price" to "anon";

grant insert on table "public"."price" to "anon";

grant references on table "public"."price" to "anon";

grant select on table "public"."price" to "anon";

grant trigger on table "public"."price" to "anon";

grant truncate on table "public"."price" to "anon";

grant update on table "public"."price" to "anon";

grant delete on table "public"."price" to "authenticated";

grant insert on table "public"."price" to "authenticated";

grant references on table "public"."price" to "authenticated";

grant select on table "public"."price" to "authenticated";

grant trigger on table "public"."price" to "authenticated";

grant truncate on table "public"."price" to "authenticated";

grant update on table "public"."price" to "authenticated";

grant delete on table "public"."price" to "service_role";

grant insert on table "public"."price" to "service_role";

grant references on table "public"."price" to "service_role";

grant select on table "public"."price" to "service_role";

grant trigger on table "public"."price" to "service_role";

grant truncate on table "public"."price" to "service_role";

grant update on table "public"."price" to "service_role";

grant delete on table "public"."product_image" to "anon";

grant insert on table "public"."product_image" to "anon";

grant references on table "public"."product_image" to "anon";

grant select on table "public"."product_image" to "anon";

grant trigger on table "public"."product_image" to "anon";

grant truncate on table "public"."product_image" to "anon";

grant update on table "public"."product_image" to "anon";

grant delete on table "public"."product_image" to "authenticated";

grant insert on table "public"."product_image" to "authenticated";

grant references on table "public"."product_image" to "authenticated";

grant select on table "public"."product_image" to "authenticated";

grant trigger on table "public"."product_image" to "authenticated";

grant truncate on table "public"."product_image" to "authenticated";

grant update on table "public"."product_image" to "authenticated";

grant delete on table "public"."product_image" to "service_role";

grant insert on table "public"."product_image" to "service_role";

grant references on table "public"."product_image" to "service_role";

grant select on table "public"."product_image" to "service_role";

grant trigger on table "public"."product_image" to "service_role";

grant truncate on table "public"."product_image" to "service_role";

grant update on table "public"."product_image" to "service_role";

create policy "allow for authenticated"
on "public"."Contact"
as permissive
for all
to public
using (true);


create policy "permissive for authenticated"
on "public"."Post"
as permissive
for all
to authenticated
using (true);


create policy "allow for authenticated"
on "public"."Product_Category"
as permissive
for select
to public
using (true);


create policy "allow for authenticated"
on "public"."country"
as permissive
for all
to authenticated
using (true);


create policy "allow authenitcated Users do all operations"
on "public"."product_image"
as permissive
for all
to authenticated
using (true);



