alter table "_realtime"."tenants" drop column "enable_authorization";

alter table "_realtime"."tenants" drop column "jwt_jwks";


drop policy "Enable insert for authenticated users only" on "public"."Product";

drop policy "Enable read for authenticated users only" on "public"."Product";

revoke delete on table "public"."Product" from "anon";

revoke insert on table "public"."Product" from "anon";

revoke references on table "public"."Product" from "anon";

revoke select on table "public"."Product" from "anon";

revoke trigger on table "public"."Product" from "anon";

revoke truncate on table "public"."Product" from "anon";

revoke update on table "public"."Product" from "anon";

revoke delete on table "public"."Product" from "authenticated";

revoke insert on table "public"."Product" from "authenticated";

revoke references on table "public"."Product" from "authenticated";

revoke select on table "public"."Product" from "authenticated";

revoke trigger on table "public"."Product" from "authenticated";

revoke truncate on table "public"."Product" from "authenticated";

revoke update on table "public"."Product" from "authenticated";

revoke delete on table "public"."Product" from "service_role";

revoke insert on table "public"."Product" from "service_role";

revoke references on table "public"."Product" from "service_role";

revoke select on table "public"."Product" from "service_role";

revoke trigger on table "public"."Product" from "service_role";

revoke truncate on table "public"."Product" from "service_role";

revoke update on table "public"."Product" from "service_role";

alter table "public"."Product" drop constraint "public_Product_category_fkey";

alter table "public"."product_variant" drop constraint "public_product_variant_product_id_fkey";

alter table "public"."Product" drop constraint "Product_pkey";

drop index if exists "public"."Product_pkey";

drop table "public"."Product";

create table "public"."product" (
    "id" integer not null default nextval('"Product_id_seq"'::regclass),
    "name" text not null default ''::text,
    "description" text default ''::text,
    "category" bigint,
    "active" boolean not null default true,
    "abbreviation" text not null default ''::text
);


alter table "public"."product" enable row level security;

create table "public"."product_component" (
    "id" bigint generated by default as identity not null,
    "main" integer not null,
    "component" integer not null
);


alter table "public"."product_component" enable row level security;

alter sequence "public"."Product_id_seq" owned by "public"."product"."id";

CREATE UNIQUE INDEX product_component_pkey ON public.product_component USING btree (id);

CREATE UNIQUE INDEX "Product_pkey" ON public.product USING btree (id);

alter table "public"."product" add constraint "Product_pkey" PRIMARY KEY using index "Product_pkey";

alter table "public"."product_component" add constraint "product_component_pkey" PRIMARY KEY using index "product_component_pkey";

alter table "public"."product" add constraint "public_Product_category_fkey" FOREIGN KEY (category) REFERENCES "Product_Category"(id) ON UPDATE CASCADE not valid;

alter table "public"."product" validate constraint "public_Product_category_fkey";

alter table "public"."product_component" add constraint "public_product_component_component_fkey" FOREIGN KEY (component) REFERENCES product(id) not valid;

alter table "public"."product_component" validate constraint "public_product_component_component_fkey";

alter table "public"."product_component" add constraint "public_product_component_main_fkey" FOREIGN KEY (main) REFERENCES product(id) not valid;

alter table "public"."product_component" validate constraint "public_product_component_main_fkey";

alter table "public"."product_variant" add constraint "public_product_variant_product_id_fkey" FOREIGN KEY (product_id) REFERENCES product(id) not valid;

alter table "public"."product_variant" validate constraint "public_product_variant_product_id_fkey";

grant delete on table "public"."product" to "anon";

grant insert on table "public"."product" to "anon";

grant references on table "public"."product" to "anon";

grant select on table "public"."product" to "anon";

grant trigger on table "public"."product" to "anon";

grant truncate on table "public"."product" to "anon";

grant update on table "public"."product" to "anon";

grant delete on table "public"."product" to "authenticated";

grant insert on table "public"."product" to "authenticated";

grant references on table "public"."product" to "authenticated";

grant select on table "public"."product" to "authenticated";

grant trigger on table "public"."product" to "authenticated";

grant truncate on table "public"."product" to "authenticated";

grant update on table "public"."product" to "authenticated";

grant delete on table "public"."product" to "service_role";

grant insert on table "public"."product" to "service_role";

grant references on table "public"."product" to "service_role";

grant select on table "public"."product" to "service_role";

grant trigger on table "public"."product" to "service_role";

grant truncate on table "public"."product" to "service_role";

grant update on table "public"."product" to "service_role";

grant delete on table "public"."product_component" to "anon";

grant insert on table "public"."product_component" to "anon";

grant references on table "public"."product_component" to "anon";

grant select on table "public"."product_component" to "anon";

grant trigger on table "public"."product_component" to "anon";

grant truncate on table "public"."product_component" to "anon";

grant update on table "public"."product_component" to "anon";

grant delete on table "public"."product_component" to "authenticated";

grant insert on table "public"."product_component" to "authenticated";

grant references on table "public"."product_component" to "authenticated";

grant select on table "public"."product_component" to "authenticated";

grant trigger on table "public"."product_component" to "authenticated";

grant truncate on table "public"."product_component" to "authenticated";

grant update on table "public"."product_component" to "authenticated";

grant delete on table "public"."product_component" to "service_role";

grant insert on table "public"."product_component" to "service_role";

grant references on table "public"."product_component" to "service_role";

grant select on table "public"."product_component" to "service_role";

grant trigger on table "public"."product_component" to "service_role";

grant truncate on table "public"."product_component" to "service_role";

grant update on table "public"."product_component" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."product"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read for authenticated users only"
on "public"."product"
as permissive
for select
to authenticated
using (true);


create policy "Enable all for authenticated users only"
on "public"."product_component"
as permissive
for all
to authenticated
using (true)
with check (true);



