create table "public"."incoterms" (
    "id" smallint generated by default as identity not null,
    "term" text not null,
    "name" text not null,
    "descr" text
);


alter table "public"."incoterms" enable row level security;

alter table "public"."opportunity" alter column "buyer" drop not null;

alter table "public"."opportunity" alter column "contact" drop not null;

CREATE UNIQUE INDEX incoterms_pkey ON public.incoterms USING btree (id);

CREATE UNIQUE INDEX incoterms_term_key ON public.incoterms USING btree (term);

alter table "public"."incoterms" add constraint "incoterms_pkey" PRIMARY KEY using index "incoterms_pkey";

alter table "public"."incoterms" add constraint "incoterms_term_key" UNIQUE using index "incoterms_term_key";

grant delete on table "public"."incoterms" to "anon";

grant insert on table "public"."incoterms" to "anon";

grant references on table "public"."incoterms" to "anon";

grant select on table "public"."incoterms" to "anon";

grant trigger on table "public"."incoterms" to "anon";

grant truncate on table "public"."incoterms" to "anon";

grant update on table "public"."incoterms" to "anon";

grant delete on table "public"."incoterms" to "authenticated";

grant insert on table "public"."incoterms" to "authenticated";

grant references on table "public"."incoterms" to "authenticated";

grant select on table "public"."incoterms" to "authenticated";

grant trigger on table "public"."incoterms" to "authenticated";

grant truncate on table "public"."incoterms" to "authenticated";

grant update on table "public"."incoterms" to "authenticated";

grant delete on table "public"."incoterms" to "service_role";

grant insert on table "public"."incoterms" to "service_role";

grant references on table "public"."incoterms" to "service_role";

grant select on table "public"."incoterms" to "service_role";

grant trigger on table "public"."incoterms" to "service_role";

grant truncate on table "public"."incoterms" to "service_role";

grant update on table "public"."incoterms" to "service_role";

create policy "authenticated_access_opportunity"
on "public"."opportunity"
as permissive
for all
to authenticated
using (true);



