create table "public"."product_variant" (
    "id" bigint generated by default as identity not null,
    "product_id" integer not null,
    "name" text not null,
    "description" text,
    "weight" integer,
    "dimension" integer,
    "material" integer
);


alter table "public"."product_variant" enable row level security;

create table "public"."product_variant_manufacturer" (
    "manufacturer_id" integer not null,
    "product_variant_id" bigint generated by default as identity not null,
    "price" real not null default '0'::real,
    "currency" "Currency" not null default 'USD'::"Currency"
);


alter table "public"."product_variant_manufacturer" enable row level security;

CREATE UNIQUE INDEX product_variant_manufacturer_pkey ON public.product_variant_manufacturer USING btree (manufacturer_id, product_variant_id);

CREATE UNIQUE INDEX product_variant_pkey ON public.product_variant USING btree (id);

alter table "public"."product_variant" add constraint "product_variant_pkey" PRIMARY KEY using index "product_variant_pkey";

alter table "public"."product_variant_manufacturer" add constraint "product_variant_manufacturer_pkey" PRIMARY KEY using index "product_variant_manufacturer_pkey";

alter table "public"."product_variant" add constraint "public_product_variant_product_id_fkey" FOREIGN KEY (product_id) REFERENCES "Product"(id) not valid;

alter table "public"."product_variant" validate constraint "public_product_variant_product_id_fkey";

alter table "public"."product_variant_manufacturer" add constraint "public_product_variant_manufacturer_manufacturer_id_fkey" FOREIGN KEY (manufacturer_id) REFERENCES "Account"(id) not valid;

alter table "public"."product_variant_manufacturer" validate constraint "public_product_variant_manufacturer_manufacturer_id_fkey";

alter table "public"."product_variant_manufacturer" add constraint "public_product_variant_manufacturer_product_variant_id_fkey" FOREIGN KEY (product_variant_id) REFERENCES product_variant(id) not valid;

alter table "public"."product_variant_manufacturer" validate constraint "public_product_variant_manufacturer_product_variant_id_fkey";

grant delete on table "public"."product_variant" to "anon";

grant insert on table "public"."product_variant" to "anon";

grant references on table "public"."product_variant" to "anon";

grant select on table "public"."product_variant" to "anon";

grant trigger on table "public"."product_variant" to "anon";

grant truncate on table "public"."product_variant" to "anon";

grant update on table "public"."product_variant" to "anon";

grant delete on table "public"."product_variant" to "authenticated";

grant insert on table "public"."product_variant" to "authenticated";

grant references on table "public"."product_variant" to "authenticated";

grant select on table "public"."product_variant" to "authenticated";

grant trigger on table "public"."product_variant" to "authenticated";

grant truncate on table "public"."product_variant" to "authenticated";

grant update on table "public"."product_variant" to "authenticated";

grant delete on table "public"."product_variant" to "service_role";

grant insert on table "public"."product_variant" to "service_role";

grant references on table "public"."product_variant" to "service_role";

grant select on table "public"."product_variant" to "service_role";

grant trigger on table "public"."product_variant" to "service_role";

grant truncate on table "public"."product_variant" to "service_role";

grant update on table "public"."product_variant" to "service_role";

grant delete on table "public"."product_variant_manufacturer" to "anon";

grant insert on table "public"."product_variant_manufacturer" to "anon";

grant references on table "public"."product_variant_manufacturer" to "anon";

grant select on table "public"."product_variant_manufacturer" to "anon";

grant trigger on table "public"."product_variant_manufacturer" to "anon";

grant truncate on table "public"."product_variant_manufacturer" to "anon";

grant update on table "public"."product_variant_manufacturer" to "anon";

grant delete on table "public"."product_variant_manufacturer" to "authenticated";

grant insert on table "public"."product_variant_manufacturer" to "authenticated";

grant references on table "public"."product_variant_manufacturer" to "authenticated";

grant select on table "public"."product_variant_manufacturer" to "authenticated";

grant trigger on table "public"."product_variant_manufacturer" to "authenticated";

grant truncate on table "public"."product_variant_manufacturer" to "authenticated";

grant update on table "public"."product_variant_manufacturer" to "authenticated";

grant delete on table "public"."product_variant_manufacturer" to "service_role";

grant insert on table "public"."product_variant_manufacturer" to "service_role";

grant references on table "public"."product_variant_manufacturer" to "service_role";

grant select on table "public"."product_variant_manufacturer" to "service_role";

grant trigger on table "public"."product_variant_manufacturer" to "service_role";

grant truncate on table "public"."product_variant_manufacturer" to "service_role";

grant update on table "public"."product_variant_manufacturer" to "service_role";


